### ISSUE TITLE
Why I'm getting this error?

### ISSUE THREAD

**Issue by jmverges** [icebob/vue-form-generator#160]
Hi there guys,

I'm getting the following and I don't get why. Anyone knows could it be?

[Vue warn]: existing instance property "errors" will be overwritten by a computed property with the same name. 
(found in component <VueFormGenerator>)
[Vue warn]: Error when rendering component <VueFormGenerator>: 
Uncaught TypeError: this.errors.filter is not a function

Best,
Juan Manuel.

**Comment by cristijora** [comment]
Are you using Vee-Validate ?

**Comment by jmverges** [comment]
yes

**Comment by cristijora** [comment]
This error appears due to the fact that Vee-Validate injects by default an `error` property everywhere basically (in each component) and globally. Internally vue-form-generator has some computed property named `errors` which is overwritten by Vee-Validate and blows up everything.
In order to get rid of this issue totally you have to rename the default `errors` from vee-validate
http://vee-validate.logaretm.com/index.html#configuration
```
const config = {
  errorBagName: 'validationErrors', // change if property conflicts.
}

Vue.use(VeeValidate, config);
```

Also make sure to RENAME `errors` everywhere you try to access them. (e.g validationErrors.has, validationErrors.first etc)

**Comment by jmverges** [comment]
Thank you so much @cristijora !!
