### ISSUE TITLE
Less dependency ? More modularity ?

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#18]
Hello,

I was wandering if it could be possible to use less dependency or smaller, more focused one. For example, what is the use of jQuery ? Why Bootstrap ?
It is something that is actually stopping me from using this component, because I don't want to bloat my web app with jQuery and Bootstrap. It's a shame really because I really need the functionality provided by your component.

Also, I could be awesome if we could choose the kind of input in a more modular way.
For example, if I don't use range slider fields, I could avoid ion.rangeSlider. If I want to use noUiSlider instead, I could create a new submodule easily. It seem to be already possible, but I wanted to be sure.

I'm ready to help, if you think this is technically possible.
Thank you for your hard work.

**Comment by icebob** [comment]
Hello,

jQuery and Bootstrap is not required dependent, just optional. If you want to use bootstrap-based optional components, you need load these libraries too.
If you [see](https://github.com/icebob/vue-form-generator/search?utf8=%E2%9C%93&q=jquery) jquery is not used in the components. Just in the examples. But I plan to change the bootstrap-* components to other vanillaJS components. E.g bootstrap-select to [vue-multiselect](https://github.com/monterail/vue-multiselect)

Shortly, if you don't load jQuery & Bootstrap, you can use the 13 built-in fields properly.
Like this: https://jsfiddle.net/0mg1v81e/13/
If I remove bootstrap it will be ugly, need some CSS, but working :)

Btw I'm accept any help, because I'm working other projects too.

**Comment by lionel-bijaoui** [comment]
Okay, sorry, it wasn't very clear that you could do without them from the Doc/Readme.
That perfect ! I'm going to test the component in my project and start styling.

vue-multiselect would be fantastic. I'm going to look at the source code and see if I can help with that. I'm not a super ninja dev so don't expect great/fast/any result from this. :no_mouth: 

Thanks a lot for your fast answer !

**Comment by icebob** [comment]
:+1: Happy testing :)

**Comment by lionel-bijaoui** [comment]
I understand you are working toward the 0.4.0, but I would like to continue toward less dependency.
My main goal is to get rid of jQuery. So I need to implement bootstrap based field using other lib. I'm choosing the most popular equivalent (most stars on github).
Remaining fields:
- DateTime field -> [Pikaday](https://github.com/dbushell/Pikaday)
- Masked input field -> [VanillaMasker](https://github.com/BankFacil/vanilla-masker)
- Slider field -> [noUiSlider](https://github.com/leongersen/noUiSlider)

**Comment by icebob** [comment]
@lionel-bijaoui it's great idea. I want to independent from bootstrap too. I create a new issue about it and create a new branch because it is a bigger development. Right?

**Comment by lionel-bijaoui** [comment]
Ok :sunglasses:

**Comment by icebob** [comment]
#31
