### ISSUE TITLE
phone number validator

### ISSUE THREAD

**Issue by obiwarn** [icebob/vue-form-generator#229]
I couldnt find a phone number validator, or am I missing something?

e.g.

+49 175 88 777

**Comment by lionel-bijaoui** [comment]
For formatting you need to use [Cleave](https://icebob.gitbooks.io/vueformgenerator/content/fields/cleave.html) or [Masked](https://icebob.gitbooks.io/vueformgenerator/content/fields/masked.html).
For validation, you need to use the regexp validator or a custom one, sorry !

Phone validation is very complex and varies depending on countries.
I don't know if it is missing on purpose or not. @icebob ?

**Comment by icebob** [comment]
I think also the Cleave is cover this issue.

**Comment by lionel-bijaoui** [comment]
Well, if you put only half your number for example, will it trigger a validation error ?
I'm not sure `require` validator is enough.
We already have a `creditCard` validator, why not add a `phone` validator ? Or remove the `creditCard` validator and let people use their custom validator ?

**Comment by lionel-bijaoui** [comment]
I will add [libphonenumber-js](https://github.com/halt-hammerzeit/libphonenumber-js) and [google-libphonenumber](https://github.com/seegno/google-libphonenumber) in the meantime.
These are robust library built upon the work of Google.

You could do a pretty simple [custom validator](https://icebob.gitbooks.io/vueformgenerator/validation/custom-validators.html) with [this](https://github.com/halt-hammerzeit/libphonenumber-js#isvalidnumberparsed_number).

My opinion is that since now users have an easy way to add custom validator and that these kind of validation are complex, we should remove `creditCard`, `url` and `email` validators.
We could create dedicated repo for each of those, that rely on other specialized library.

**Comment by dflock** [comment]
On the other hand, `creditCard`, `url` and `email` validation is quite common, so maybe we should support the common case out-of-the-box?

At least for credit card validation, it's a de-facto global standard, fairly simple to support and requires no extra dependencies. It's very hard to formally, correctly, validate email addresses & urls, so our validators only do simple, common case validation of these.

The bundled validators also make good examples for people wanting to implement their own custom validators.

I'd be open to making things more modular, provided that it doesn't make it harder for people to get started - so no extra setup work for the user, etc...

Also, libphonenumber.js is 418 Kb... ?

**Comment by obiwarn** [comment]
I used the hammerzeit libphonenumber. It says it is only 75 Kb.

https://www.npmjs.com/package/libphonenumber-js

IMHO I would include `phone` as a validator. Quite common.

**Comment by lionel-bijaoui** [comment]
@obiwarn Maybe you could give us a hand an do a PR for that ?
That would be really nice of you to do that.
[Check this file to get started](https://github.com/icebob/vue-form-generator/blob/master/src/utils/validators.js).
Good luck !

**Comment by cesarmarinhorj** [comment]
I am doing this with regexp, a simple a pattern resolves to me.
