### ISSUE TITLE
Label not showing on image input

### ISSUE THREAD

**Issue by pardmeister** [icebob/vue-form-generator#235]
Hi

The label on my image input is not showing. My code is below:

```
{
    type: 'image',
    label: 'Identity document',
    hideInput: true,
    preview: true,
    model: 'id_document',
    required: true,
    styleClasses: 'col-sm-12'
}
```

Also, is there a more detailed tutorial in styling the forms?

Thanks
Pard

**Comment by lionel-bijaoui** [comment]
Can you provide a Fiddle ?
It will be easier to find a solution that way.
Thank you.

**Comment by pardmeister** [comment]
Will do, still reading up on creating fiddles.

**Comment by pardmeister** [comment]
Hi Lionel

Hope this works. By the way, this is a great component, thanks for the great work guys.

https://jsfiddle.net/kbg6gbyc/4/

**Comment by lionel-bijaoui** [comment]
FYI you can add the css of VFG with [this link](https://unpkg.com/vue-form-generator@2.0.0-beta5/dist/vfg.css), no need to copy and paste it directly.
I updated [your fiddle](https://jsfiddle.net/kbg6gbyc/6/) accordingly.

I seem to be [a feature](https://github.com/icebob/vue-form-generator/blob/master/src/formGenerator.vue#L205).
I didn't knew this existed and I don't know why this is here.
@icebob can you explain this choice ? I don't see the need to prevent people from adding label to a field, even if it may be a bad idea.
We should remove that, since it add limitation for no clear reason.

**Comment by pardmeister** [comment]
Yes, I noticed in this piece of code:

```
// Should field type have a label?
			fieldTypeHasLabel(field) {
				let relevantType = "";
				if (field.type === "input") {
					relevantType = field.inputType;
				} else {
					relevantType = field.type;
				}

				switch (relevantType) {
				case "button":
				case "image":
				case "submit":
				case "reset":
					return false;
				default:
					return true;
				}
```

Should have just posted that actually

**Comment by pardmeister** [comment]
Thanks for the assistance lionel

**Comment by lionel-bijaoui** [comment]
You are welcome 👍 
Next time, yeah, start with that 😆

**Comment by pardmeister** [comment]
Hi

Has this been updated, or is there a valid reason why an image input should not have a label?

**Comment by lionel-bijaoui** [comment]
Sorry, I'm waiting on @icebob answer to fix this (or not if it is indeed a feature that make sense).

**Comment by icebob** [comment]
Hmm, I think it is a bug. Need to remove the `image` from the switch case.

**Comment by icebob** [comment]
@pardmeister Could you make a PR with fix?

**Comment by pardmeister** [comment]
@icebob Not a problem.

**Comment by pardmeister** [comment]
Done, please review when you have time.

**Comment by icebob** [comment]
Thank you. Merged.
