### ISSUE TITLE
Markdown in labels

### ISSUE THREAD

**Issue by Dubaua** [icebob/vue-form-generator#250]
Is it possible to make labels with markdown? I need to insert link to one of my labels (privacy politics)

**Comment by cristijora** [comment]
From what I know, currently it's not possible to have markdown in labels. I think it's easier to make your own field which will contain markdown or dynamic html. Depending on how often you need this feature it might be introduced but only in a component form and not markdown.

```
label:{
 template: `<span>This is my <b>bold text</b></span>
}
```

**Comment by icebob** [comment]
Or you can use `help` or `hint` prop. The `help` supports HTML tags.

https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html

**Comment by Dubaua** [comment]
@cristijora Thank you. I'll try.

**Comment by Dubaua** [comment]
I tried

`var privacy = {
    label: {
        template: '<span>This is my <b>bold text</b></span>'
    },
};

var app = new Vue({
    el: '#app',
    mixins: [privacy],
    components: {
        'vue-form-generator': VueFormGenerator.component
    },
   ...`
That doesn't work.
I know that I missed something important, but I don't know what.

**Comment by cristijora** [comment]
@Dubaua Maybe I didn't express myself very clear here but that was more of an idea/suggestion to implement rather than an implementation detail
The only thing that support html now is the `hint` field 
![image](https://user-images.githubusercontent.com/15955045/27920451-48233fbe-627d-11e7-92e8-b83a21e089f7.png)
https://jsfiddle.net/0mg1v81e/526/

My example is just a suggestion which is not implemented
