### ISSUE TITLE
Trigger validation on specific event

### ISSUE THREAD

**Issue by jarvelov** [icebob/vue-form-generator#264]
Is there any way to trigger validation on a specific event, e.g blur, input etc.?

**Comment by lionel-bijaoui** [comment]
Since some fields don't use HTML input, blur or focus is not always available and we can't do that. For now, it is either at load, on value change or manual.
I guess you could work something with class to attach event to inputs, event that would trigger "manual" validation. Not sure it would work. Gook luck !

**Comment by DelfsEngineering** [comment]
Could this be handled with a custom component?
Perhaps the custom component can fire an event or soemthing? What would it need to fire to trigger the custom validation validation code?

**Comment by cristijora** [comment]
@DelfsEngineering you can see the example here https://jsfiddle.net/0mg1v81e/607/
Upon value changing, each field calls a method `validate()` which is available in the `abstractFieldMixin`
You could use that on your custom component to trigger validation for your field whenever you need it (e.g blur or other kind of event)

**Comment by DelfsEngineering** [comment]
@cristijora Thanks, That works for text inputs, what can I use for Radio Buttons? I think that is more common too for conditional forms.
