### ISSUE TITLE
noUIslider tooltips option is ignored.

### ISSUE THREAD

**Issue by Aterr** [icebob/vue-form-generator#351]
Hello there!
It seems like all slider options are ignored. Can you please check this ?

I am using it the way, described in docs.
```
{
                    type: "noUiSlider",
                    label: "Volume level",
                    model: "volume",
                    min: 0,
                    max: 140,
                    sliderOptions: {
                      connect: "lower",
                      step: 10,
                      tooltips: [true],
                    },
}

**Comment by Aterr** [comment]
Is anybody alive here ? :)

**Comment by lionel-bijaoui** [comment]
1. This is an open source project, maintained by volunteer on their free time, given to you and the rest world for free
2. Show some respect and patience, we are NOT at your service
3. This is the weekend
4. Provide a fiddle that reproduce the problem that you are facing, we are not telepathic wizard able to fix bugs by reading tea leaves

I'm going to assume that you are maybe new to this, and didn't realized your lack of basic respect by showing such impatient comportment.

So, please provide a fiddle that reproduce this bug, so that it is easier to fix and **wait** for an eventual answer. Again, we are not at your service.
Until then, I'm closing the issue.

**Comment by DelfsEngineering** [comment]
Well said. VFG has become the core of my app. It’s a great contribution and I can’t wait to help further  its development.

**Comment by Aterr** [comment]
Well, sorry if you did not understood me correctly. I posted this on friday morning, and on weekend I just updated this with new comment, that's all I did.
I also understand that you are not at my service, that's why I asked you for help not for someting else. And you're right I'm new with VFG. It's kinda strange that you reacted like that. II will provide a fiddle asap.

**Comment by lionel-bijaoui** [comment]
You don't seem to understand the problem with your attitude.
If you want to update a comment, there is an edit button on every comment box (the little pencil in the upper right).
The thing is, you did not update your comment to add details, show some progress or explain your issue better.
By adding another comment, you spammed every contributor with a notification, just to grab attention. This *might* be okay if you feel like you issue is being ignored for too long (at least a month of no anwser/tagging/activity), but even then, you should do this reasonably.
Coming back to you, you "waited" around 24h...

You should not be sorry that "I'm offended", you should be sorry for your lack of respect, and apologize correctly for spamming and begging for update. Stop rejecting the fault on others.
You made a mistake, this is not the end of the world.
Accept your blame, then I'm ready to excuse you and help you fix your problem.
In the end we both want to make VFG better, so let's do it ! 😄
